#### GLOBAL PACKAGES                                            ####
library(tidyverse);
library(drc);
library(car);
library(lubridate);
library(janitor);
library(broom);
library(lme4);
library(rstatix)

#### GLOBAL DATA IMPORT                                         ####
envdata<-read_tsv("data/Site Data/environment_data.txt")%>%
  clean_names()

tempdata<-readRDS("./output/tempset")%>%
  dplyr::rename(date=day)%>%
  mutate(cumulative25=case_when(cumulative25<0~0,TRUE~as.numeric(cumulative25))) #generated by temperatures.R

pamdata<-readRDS("./output/pamdata") #generated by PAM.R

metadata<-readRDS("./output/metadata") #generated by meta.R
    
survivors<-readRDS("output/frag_bleachdata")%>%
  left_join(metadata, by="id")%>%
  filter(experiment=="clonality"|experiment=="RTE")%>%
  filter(timepoint==1)%>%
  left_join(as_tibble(readRDS("output/survivors")%>%
                        dplyr::select(-group)), by="id") #generated by scores.R

frag_bleachdata<-readRDS("output/frag_bleachdata") # generated by scores.R
#### ####
#### FIGURE 1 EXPT OVERVIEW                                     ####
library(ggmap); library(sf); library(janitor); library(readxl);library(ggsn); library(ggnewscale); library(scales); library(cowplot);library("grid");library("ggplotify"); library(patchwork)

# map of survey sites in Kaneohe Bay 
oahu<-st_transform(st_read("docs/oahu_map/Layers/coast_n83.shp"),crs=4386)
cropped<-st_crop(oahu,xmin=-158.8,xmax=-157.4,ymin=20.8,ymax=21.8)
fringe<-st_read("docs/oahu_map/Layers/Fringing Reef.shp")%>%dplyr::select(id,geometry)%>%mutate(zone='Fringing Reef')
habitat<-st_read("docs/oahu_map/Layers/haw_benthic_habitat.shp")%>%clean_names()%>%dplyr::filter(zone=='Backreef'|zone=="Reef Flat")%>%dplyr::select(id,zone,geometry)
patch<-st_read("docs/oahu_map/Layers/Patches2.shp")%>%mutate(type="Reef")%>%clean_names()%>%dplyr::select(id,zone,block,geometry)%>%mutate(zone='Patch Reef')
points<-read_excel("data/Site Data/site_coordinates.xlsx")%>%dplyr::select(site,block,lat,lon)%>%mutate(block=paste("Block",as.factor(block)))

out<-bind_rows(st_transform(fringe,crs=4386),st_transform(habitat,crs=4386))%>%
  mutate(zone=case_when(zone=="Reef Flat"~ "Fringing Reef",
                        zone=="Reef Crest"~"Fringing Reef",
                        zone=="Backreef"|zone=="Fringing Reef"~"Back/Fringing Reef",
                        TRUE~as.character(zone)))

overview<-ggplotGrob(ggplot()+
                       geom_sf(data=cropped)+
                       theme_minimal(base_size=6)+
                       theme(axis.text.x=element_blank(),
                             axis.title.y=element_blank(),
                             axis.title.x=element_blank(),
                             axis.text.y=element_blank(),
                             panel.grid.minor=element_blank(),
                             panel.grid.major=element_blank(),
                             panel.border = element_rect(colour = "gray35", fill=NA, size=1),
                             panel.background = element_rect(color="white"))+
                       annotate("rect",xmin=-157.85,xmax=-157.76,ymin=21.413,ymax=21.507,color="blue",alpha=0.25,size=0.25)+
                       annotate("text",x=-158.05,y=21.52,label="Oʻahu",size=2.5))
#add a north arrow
inset_oahu<-as.grob(ggdraw()+ 
                      draw_plot(overview)+
                      draw_image("docs/oahu_map/north_arrow.png",x=0.3, y=0.3,scale=0.2))

quartz(w=2.4)
#assemble map                    
A1<-ggplot()+
  geom_sf(data=out,fill="lightgrey",color='lightgrey')+
  geom_sf(data=oahu,fill="darkgrey")+
  geom_sf(aes(fill=block,color=block),dat=patch,alpha=0.6,size=0.2)+
  coord_sf(xlim=c(-157.85,-157.76),ylim=c(21.413,21.507))+
  theme_classic(base_size=6)+
  theme(legend.position=c(0.16,0.22),
        legend.key.size=unit(0.25,"cm"),
        axis.title=element_blank(),
        axis.text.x=element_text(hjust=0.7),
        axis.text.y=element_text(angle=90,hjust=0.5))+
  scale_color_viridis_d(direction=1,guide="none")+
  scale_fill_viridis_d(direction=1,name=NULL)+
  scalebar(x.min=-157.78,x.max=-157.82,y.min=21.415,y.max=21.50,transform=TRUE,dist=1,dist_unit="km",
           height = .025, st.dist = 0.04,
           box.fill = c("black", "white"),
           box.color = "black", border.size = .1,st.size=2,
           location="bottomleft")+
  annotation_custom(inset_oahu,xmin=-157.8,xmax=-157.755,ymin=21.479,ymax=21.512)+
  geom_point(aes(lon,lat,fill=block),pch=21,data=points,fill="red",position=position_jitter(width=0.0016,height=0.0016));A1

## plot of experiment timeline
plotdata<-read_table("./data/Temperature/historical.txt")%>%rename(YY=1)%>%filter(YY!="#yr")%>%dplyr::select(YY,MM,DD,hh,mm,WTMP)%>%filter(WTMP<50)%>%unite(date,YY,MM,DD,sep="-")%>%unite(time,hh,mm,sep=":")%>%
  unite(date,date,time,sep=" ")%>%mutate(date=ymd_hm(date))%>%rename(temp=2)%>%mutate(temp=as.numeric(temp))%>%
  group_by(date(date))%>%summarise(mean=mean(temp))%>%rename(date=1)%>%
  mutate(year=as.factor(year(date)))%>%
  filter(date>='2017-06-01')%>%
  filter(date<='2019-11-30')

temperature<-tempdata%>%
  mutate(days=interval(ymd('2018-02-06'),ymd(date))%/%days(1))
write_rds(temperature, "output/stress_pofile.RDS")

ggplot(temperature, (aes (date, meantemp)))+geom_line()

pam_timeline<-read_csv("./docs/pam_collection_timeline.csv")%>%
  mutate(pam_data=case_when(pam_timepoint<=16~22.2,TRUE~NA_real_))%>%
  #date<="2018-02-27" (session 16) for PAM sessions used in analysis
  mutate(date=as.Date(date, '%m/%d/%y'))%>%
  right_join(temperature, by="date")%>%
  arrange(date)

quartz(w=4.8, h=2.4)
B1<-ggplot()+
  geom_vline(xintercept=as_date("2018-08-08"),color="gray",size= 0.8)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2017-11-10"),xmax=as_date("2018-01-26"),fill="gray",alpha=0.4)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2018-01-26"),xmax=as_date("2018-02-06"),fill="blue",alpha=0.4)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2018-02-06"),xmax=as_date("2018-02-27"),fill="red",alpha=0.4)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2018-02-27"),xmax=as_date("2018-03-09"),fill="purple",alpha=0.4)+ #purple
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2018-03-09"),xmax=as_date("2018-05-08"),fill="blue",alpha=0.4)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2018-05-08"),xmax=as_date("2018-08-08"),fill="gray",alpha=0.4)+
  annotate("rect",ymin=20,ymax=40,xmin=as_date("2019-10-03"),xmax=as_date("2019-10-21"),fill="yellow",alpha=0.4)+
  geom_line(aes(date,mean,color=mean),data=plotdata,alpha=0.6, size=0.8)+
  geom_line(data=temperature, aes(x=date, y=meantemp,color=meantemp),size=0.8)+#,color="red"
  geom_hline(yintercept=28.5,linetype="dashed",color="grey30", size=0.5)+
  scale_color_gradient2(low="black",mid="blue",high="red",name="Temperature",midpoint=26,guide="none")+
  scale_x_date(date_breaks="3 months",minor_breaks=waiver(),date_labels="%b-%Y",limits=c(as.Date("2017-07-1"),as.Date("2019-12-1")),expand=c(0.02,0.02))+
  ylab("Temp (°C)")+
  theme_classic(base_size=6)+
  coord_cartesian(ylim=c(21,32.5),xlim=c(as_date("2017-06-01"),as_date("2019-11-31")))+
  scale_y_continuous(breaks=c(22,24,26,28,30,32))+
  theme(axis.title.y = element_text(margin = margin(r = 5)))+
  theme(axis.title.x=element_blank())+
  annotate("segment", x=as_date("2019-8-10"), xend=as_date("2019-10-21"), y=29.9,yend=29.9,color="red",size=1)+
  annotate("segment", x=as_date("2017-7-1"), xend=as_date("2019-3-30"), y=33,yend=33,color="black",size=1)+
  annotate("segment", x=as_date("2017-7-3"), xend=as_date("2017-7-3"), y=33,yend=32.5,color="black",size=0.9)+
  annotate("segment", x=as_date("2019-3-28"), xend=as_date("2019-3-28"), y=33,yend=32.5,color="black",size=0.9)+
  annotate("segment",x=as_date("2018-01-10"),xend=as_date("2018-02-18"),y=31,yend=31,color="grey30",size =0.4, arrow=arrow(length=unit(0.1, "cm")))+
  annotate("segment",x=as_date("2018-09-18"),xend=as_date("2018-08-08"),y=22,yend=22,color="grey30",size=0.4,arrow=arrow(length=unit(0.1, "cm")))+
  annotate("segment",x=as_date("2019-9-01"),xend=as_date("2019-10-13"),y=22,yend=22,color="grey30",size=0.4,arrow=arrow(length=unit(0.1, "cm")))+
  annotate("text",x=as_date("2017-07-05"),label="MMM +1°C",y=28.8,color="grey30", size=2)+
  annotate("text",x=as_date("2017-08-15"),label=stringr::str_wrap("Ambient Temperature", width = 10),color="grey30",y=26.6,size=2)+
  annotate("text",x=as_date("2019-09-16"),label="Coral Bleaching Event",y=30.4,size=2)+
  annotate("text",x=as_date("2018-11-30"),label="Field Site Temperature Data",y=32.5,size=2)+
  annotate("text",x=as_date("2018-9-24"),y=22,label= stringr::str_wrap("Experiment Survivorship Assessement",width = 12),hjust=0, size=2)+
  annotate("text",x=as_date("2017-11-02"),y=22,label= stringr::str_wrap("Field Sample Collection",width = 8),hjust=1,size=2)+
  annotate("text",x=as_date("2019-08-28"),y=22,label= stringr::str_wrap("Field Bleaching Assessment",width = 12),hjust=1, size=2)+
  annotate("text",x=as_date("2017-11-20"),y=31,label= stringr::str_wrap("Heat Stress Profile",width = 4),hjust=0, size=2);B1

quartz(w=7.2, h=2.7)
Fig1AB<-A1 + B1 + plot_layout(ncol = 2, nrow =1);Fig1AB

quartz(w=7.2, h=2.4)
Fig1AB<-A1 + B1 + plot_layout(ncol = 2, nrow =1);Fig1AB

## detail of experiment 
quartz(w=7.2, h=0.85)
quartz(w=7.2, h=2)
C1<-ggplot(pam_timeline, aes(x=days, y=meantemp))+
  theme_classic(base_size=12)+
  annotate("rect",ymin=21.5,ymax=34,xmin=-6,xmax=0,fill="blue",alpha=0.2)+
  annotate("rect",ymin=21.5,ymax=34,xmin=0,xmax=21,fill="red",alpha=0.2)+
  annotate("rect",ymin=21.5,ymax=34,xmin=21,xmax=32,fill="purple",alpha=0.2)+
  annotate("rect",ymin=21.5,ymax=34,xmin=32,xmax=35.3,fill="blue",alpha=0.2)+
  geom_point(color="red", size = 1.2)+
  geom_line(color="red",size=1)+
  ylab("Temp (°C)")+
  #xlab("Days")+
  theme(axis.title.y = element_text(margin = margin(r = 5)))+
  theme(axis.title.x=element_blank())+
  scale_y_continuous(breaks=c(24,26,28,30,32),expand=c(0,0),limits=c(21.5,34))+
  #theme(axis.title.x = element_text(hjust = 0))+
  geom_point(aes(days,pam_data),shape=17, size=2.2, color="black")+
  #annotate("text",x=12,y=25.5,label= "PAM readings", size=2.2)+
  scale_x_continuous(breaks=c(0,10,20,30),limits=c(-6,35.3),expand=c(0,0),position="top");C1
    
rm(A1,B1,C1, cropped, Fig1AB, fringe, habitat, inset_oahu, oahu, out, overview, pam_timeline, patch, plotdata, points,temperature)

#### ####
#### PAM MODEL SELECTION (CHOOSES W1.3)                         #####
drcdat_pam<-left_join(pamdata,tempdata,by="date")%>%left_join(.,metadata,by="id")%>%
  filter(date<="2018-02-27")%>%
  filter(experiment =="clonality"| experiment=="RTE")

# iteratively remove models with poor fitting
best_fit_pam<-data.frame(best=character())
for (i in unique(drcdat_pam$id)){
  temp<-drcdat_pam%>%filter(id==paste0(i))%>%ungroup()
  model<-drm(relative~cumulative25,data=temp,fct=W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")));#plot(model)
  best<-(as.data.frame(mselect(model, fctList = list(W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     #W1.4(fixed=c(NA,NA,1,NA),names = c("Slope","Lower Limit","Upper Limit","ED50")),
                                                     #W2.4(fixed=c(NA,NA,1,NA),names = c("Slope","Lower Limit","Upper Limit","ED50")),
                                                     ##LL.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     ##EXD.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     ##EXD.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     ##AR.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     ##MM.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     LL.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50"))
  )))
  %>%rownames_to_column())[1,1]
  best_fit_pam<-best_fit_pam%>%add_row(best=best)
}
table(best_fit_pam$best)

#LL.3 W1.3 W2.3 
#26  252   31 

#USE W1.3 with Upper Limit fixed at 1 


#### PAM MODEL ED LEVEL SELECTION (CHOOSES ~ED20)               ####
drcdat_pam_clone<-left_join(pamdata,tempdata,by="date")%>%
  left_join(.,metadata,by="id")%>%
  filter(fv_fm>0.2)%>%#restrict to meaningful pam values
  #filter(id!=2314,id!=3114,id!=754)%>%#comment why these samples are problematic
  filter(date<="2018-02-27")%>% #restrict to heat stress period
  filter(experiment=="clonality") #ed optimization is for this group

ED_pam<-data.frame(id=character(),
                   ed_level=numeric(),
                   ed=numeric(),
                   se=numeric(),
                   lwr=numeric(),
                   uppr=numeric(),
                   slope=numeric())
fits<-data.frame(ed=numeric(),
                 lm_r2=numeric())

for (j in seq(1,50,1)){
  for (i in unique(drcdat_pam_clone$id)){
    temp<-drcdat_pam_clone%>%
      filter(id==paste0(i))%>%
      ungroup()
    
    model<-drm(relative~cumulative25,
               data=temp,
               fct=W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
    
    summary<-ED(model, c(j), interval = "delta")
    ED_pam<-ED_pam%>%add_row(id=i,
                             ed_level=j,
                             ed=summary[1],
                             se=summary[2],
                             lwr=summary[3],
                             uppr=summary[4],
                             slope=model$coefficients[1])
  }
  working<-left_join(ED_pam%>%filter(se!="NaN",slope>1,ed<75),#filter ED by non convergence
                     metadata,
                     by="id")%>%
    dplyr::select(id,ed_level,ed,mean_bleach)%>%
    filter(ed_level==j)%>%
    drop_na()
  lm<-lm(mean_bleach ~ed,data=working)
  fits<-fits%>%add_row(ed=j,lm_r2=as.numeric(glance(lm)[1]))
}

ED_pam_clean<-ED_pam%>%filter(se!="NaN", slope>1, ed<75)
pam_fits_plot<-ggplot(fits,aes(x=ed,y=lm_r2))+geom_bar(stat="identity");pam_fits_plot
#saveRDS(fits, "./output/edfits_pam")
#saveRDS(ED_pam_clean,"./output/ED_values_pam_clonality")
rm(best_fit_pam, drcdat_pam, drcdat_pam_clone, ED_pam, ED_pam_clean, fits, lm, model, pam_fits_plot, summary, temp, working, best, i, j)

#### PAM MODEL FITS                                             ####
#make and save model curve fits for all samples in data set
best_ed_value= 20  #set ed level
ed.level<-paste0("ed", best_ed_value)
drcdat_pam_all<-left_join(pamdata,tempdata,by="date")%>%
  left_join(.,metadata,by="id")%>%
  filter(fv_fm>0.2)%>%#restrict to meaningful pam values
  filter(id!=2314,id!=3114,id!=754)%>%#comment why these samples are problematic or add tryCatch in loop
  filter(date<="2018-02-27")%>% #restrict to heat stress period
  filter(experiment =="clonality"| experiment=="RTE")


out_pam_all<-data.frame(id=character(),
                        duration=numeric(),
                        predicted=numeric(),
                        pmin=numeric(),
                        pmax=numeric())

ED_pam_all<-data.frame(id=character(),
                       ed=numeric(),
                       se=numeric(),
                       lwr=numeric(),
                       uppr=numeric(),
                       slope=numeric())

for (i in unique(drcdat_pam_all$id)){
  temp<-drcdat_pam_all%>%
    filter(id==paste0(i))%>%
    ungroup()
  model<-drm(relative~cumulative25,
             data=temp,
             fct=W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
  summary<-ED(model, c(best_ed_value), interval = "delta")
  ED_pam_all<-ED_pam_all%>%add_row(id=i,
                                   ed=summary[1],
                                   se=summary[2],
                                   lwr=summary[3],
                                   uppr=summary[4],
                                   slope=model$coefficients[1])
  
  newdata<-expand.grid(accumulated=seq(#min(drcdat_pam_all$cumulative25),
    #max(drcdat_pam_all$cumulative25),
    0,
    30,
    length=100))
  pm<-predict(model, newdata=newdata, interval="confidence")
  newdata$p<-pm[,1];newdata$pmin <- pm[,2];newdata$pmax <- pm[,3]
  out_pam_all<-out_pam_all%>%add_row(id=i,
                                     duration=newdata$accumulated,
                                     predicted=newdata$p,
                                     pmin=newdata$pmin,
                                     pmax=newdata$pmax)
}
ED_pam_clean_all<-ED_pam_all%>%filter(se!="NaN", slope>1, ed<75)
ED_pam_out_clean<-out_pam_all%>%semi_join(ED_pam_clean_all,by="id")

#saveRDS(ED_pam_out_clean,"./output/ED_pam_model")
#saveRDS(ED_pam_clean_all,paste0("./output/",ed.level,"_pam_values"))

rm(drcdat_pam_all, ED_pam_all, ED_pam_clean_all, ED_pam_out_clean, model,newdata, out_pam_all, pm,  summary, temp, best_ed_value, i, ed.level)


#### ####
#### EXPT HEALTH SCORE MODEL SELECTION (CHOOSES W2.3)           ####
bleach_frag<-frag_bleachdata%>%
  left_join(metadata, by="id")%>%
  dplyr::filter(experiment=="clonality")%>%
  left_join(survivors%>%dplyr::select(id,survivor), by="id")%>%
  mutate(exp_bleach=case_when(exp_bleach<=1~1,TRUE~exp_bleach))%>%
  mutate(exp_bleach=exp_bleach-1)%>%
  group_by(id)%>%
  mutate(base_bleach=case_when(timepoint==1~exp_bleach,TRUE~NA_integer_))%>%
  fill(base_bleach)%>%
  mutate(prop_bleach=exp_bleach/base_bleach)%>%
  left_join(tempdata, by="date")
write_rds(bleach_frag, "output/bleach_frag")
#move to figure assembly area:
ggplot(bleach_frag)+
  geom_jitter(aes(cumulative25, prop_bleach,group=id,color=survivor), size=0.3)+
  geom_smooth(aes(cumulative25, prop_bleach, group=survivor,color=survivor),method="glm",method.args = list(family = "binomial"),se=TRUE,linewidth=0.5)+
  geom_smooth(aes(cumulative25, prop_bleach),method="glm",method.args = list(family = "quasibinomial"),se=TRUE,color="black")

best_fit_bleach<-data.frame(best=character())
for (i in unique(Bleach$id)){
  temp<-bleach_frag%>%filter(id==paste0(i))%>%ungroup()
  model<-drm(prop_bleach~cumulative25,data=temp,fct=W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")));#plot(model)
  best<-(as.data.frame(mselect(model, fctList = list(W1.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     #W1.4(fixed=c(NA,NA,1,NA),names = c("Slope","Lower Limit","Upper Limit","ED50")),
                                                     #W2.4(fixed=c(NA,NA,1,NA),names = c("Slope","Lower Limit","Upper Limit","ED50")),
                                                     LL.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     #EXD.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     #EXD.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     #AR.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     #MM.2(fixed=c(NA,1),names=c("Slope","Upper Limit")),
                                                     #LL.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")),
                                                     W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50"))
                                                     
  )))
  %>%rownames_to_column())[1,1]
  best_fit_bleach<-best_fit_bleach%>%add_row(best=best)
}
table(best_fit_bleach$best)
# W1.3 W2.3 
#  70   78 

rm(best_fit_bleach, temp, model, best, i)

#### EXPT HEALTH SCORE ED LEVEL SELECTION (No Sig.ED Value)     ####
bleach_frag<-read_rds("output/bleach_frag")
ED_bleach<-data.frame(id=character(),
                      ed_level=numeric(),
                      ed=numeric(),
                      se=numeric(),
                      lwr=numeric(),
                      uppr=numeric(),
                      slope=numeric())

fits<-data.frame(ed=numeric(),
                 lm_r2=numeric())

for (j in seq(1,50,1)){
  for (i in unique(bleach_frag$id)){
    temp<-bleach_frag%>%
      filter(id==paste0(i))%>%
      ungroup()
    
      model<-drm(prop_bleach~cumulative25,
               data=temp,
               fct=W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
    
      summary<-ED(model, c(j), interval = "delta")
      ED_bleach<-ED_bleach%>%add_row(id=i,
                                   ed_level=j,
                                   ed=summary[1],
                                   se=summary[2],
                                   lwr=summary[3],
                                   uppr=summary[4],
                                   slope=model$coefficients[1])
  }
  
    working<-left_join(ED_bleach%>%filter(se!="NaN"),#filter ED by non convergence
                     bleach_frag,
                     by="id")%>%
    dplyr::select(id,ed_level,ed,mean_bleach)%>%
    filter(ed_level==j)%>%
    drop_na()
  
  lm<-lm(ed~mean_bleach,data=working)
  fits<-fits%>%add_row(ed=j,lm_r2=as.numeric(glance(lm)[1]))
  
}

ED_bleach_clean<-ED_bleach%>%filter(se!="NaN")
score_fits_plot<-ggplot(fits,aes(x=ed,y=lm_r2))+geom_bar(stat="identity");score_fits_plot

#saveRDS(fits, "./output/edfits_health")

rm(bleach_frag, ED_bleach, ED_bleach_clean, fits, lm, score_fits_plot, working, j)

#### EXPT HEALTH SCORE MODEL FITS                               ####
bleach_frag<-read_rds("output/bleach_frag")
pick_ed_value= 20  #set ed level  # arbitrary / match PAM since no significant ED levels detected
ed.level<-paste0("ed", pick_ed_value)
out_health_all<-data.frame(id=character(),
                           duration=numeric(),
                           predicted=numeric(),
                           pmin=numeric(),
                           pmax=numeric())

ED_health_all<-data.frame(id=character(),
                          ed=numeric(),
                          se=numeric(),
                          lwr=numeric(),
                          uppr=numeric(),
                          slope=numeric())

for (i in unique(bleach_frag$id)){
  temp<-bleach_frag%>%
    filter(id==paste0(i))%>%
    ungroup()
  
  model<-drm(prop_bleach~cumulative25,
             data=temp,
             fct=W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
  
  summary<-ED(model, c(pick_ed_value), interval = "delta")
  ED_health_all<-ED_health_all%>%add_row(id=i,
                                         ed=summary[1],
                                         se=summary[2],
                                         lwr=summary[3],
                                         uppr=summary[4],
                                         slope=model$coefficients[1])
  
  newdata<-expand.grid(accumulated=seq(
    0,
    30,
    length=100))
  pm<-predict(model, newdata=newdata, interval="confidence")
  newdata$p<-pm[,1];newdata$pmin <- pm[,2];newdata$pmax <- pm[,3]
  out_health_all<-out_health_all%>%add_row(id=i,
                                           duration=newdata$accumulated,
                                           predicted=newdata$p,
                                           pmin=newdata$pmin,
                                           pmax=newdata$pmax)
}

ED_health_clean_all<-ED_health_all%>%filter(se!="NaN")
ED_health_out_clean<-out_health_all%>%semi_join(ED_health_clean_all,by="id")

#visualize:
health_fits<-left_join(ED_health_out_clean,metadata,by="id")%>%left_join(survivors, by="id")
ggplot(data=health_fits,aes(duration, predicted, group=id))+geom_line(aes(color=survivor))

#saveRDS(ED_health_out_clean,"./output/ED_health_model")
#saveRDS(ED_health_clean_all,paste0("./output/",ed.level,"_health_values"))
rm(bleach_frag,ED_health_all,ED_health_clean_all,ED_health_out_clean,health_fits,model, newdata, out_health_all, pm, summary, temp, ed.level, i, pick_ed_value)

# by survivors and non-survivors
surv_health_mod<-drm(prop_bleach~cumulative25,
                              data=bleach_frag%>%filter(survivor=="Y"),
                              fct=W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
newdata<-expand.grid(accumulated=seq(0,30,length=100))
pm<-predict(surv_health_mod, newdata=newdata, interval="confidence")
newdata$predicted<-pm[,1];newdata$pmin <- pm[,2];newdata$pmax <- pm[,3]
#saveRDS(newdata, "output/surv_health_mod")

nonsurv_health_mod<-drm(prop_bleach~cumulative25,
                     data=bleach_frag%>%filter(survivor=="N"),
                     fct=W2.3(fixed=c(NA,1,NA),names = c("Slope","Upper Limit","ED50")))
newdata<-expand.grid(accumulated=seq(0,30,length=100))
pm<-predict(nonsurv_health_mod, newdata=newdata, interval="confidence")
newdata$predicted<-pm[,1];newdata$pmin <- pm[,2];newdata$pmax <- pm[,3]
#saveRDS(newdata, "output/nonsurv_health_mod")

#### ####
#### DATAFRAMES for MODELING                                    ####
survivors<-readRDS("./output/survivors")%>%
  dplyr::select(id,survivor)
expt_bleach<-readRDS("output/frag_bleachdata")%>%
  dplyr::filter(timepoint==1)%>%
  dplyr::select(id,mean_exp_bleach)
pam_ed<-readRDS("./output/ed20_pam_values")%>%
  left_join(.,metadata,by="id")%>%
  dplyr::filter(group=="clonality")%>%
  dplyr::select(id,ed)%>%
  dplyr::rename(pam_ed=ed)
pam_initial<-pamdata%>%
  dplyr::filter(date=="2018-02-02")%>%
  left_join(.,metadata,by="id")%>%
  dplyr::filter(group=="clonality")%>%
  dplyr::select(id,initial)%>%
  dplyr::rename(initial_pam=initial)
health_ed<-readRDS("./output/ed20_health_values")%>%
  left_join(.,metadata,by="id")%>%
  dplyr::filter(group=="clonality")%>%
  dplyr::select(id,ed)%>%
  dplyr::rename(health_ed=ed)

expt_bleach<-readRDS("output/frag_bleachdata")%>%
  dplyr::filter(timepoint==1)%>%
  dplyr::select(id,mean_exp_bleach)

population_data<-metadata%>%
  dplyr::filter(experiment=="clonality", drop_clones=="keep")%>%
  left_join(envdata, by="site")%>%
  left_join(survivors, by="id")%>%
  left_join(expt_bleach, by="id")%>%
  left_join(pam_ed, by="id")%>%
  left_join(pam_initial, by="id")%>%
  left_join(health_ed, by="id")%>%
  mutate(symbiont=case_when(prop_d_2018>0.8~"D",prop_d_2018<0.2~"C",is.na(prop_d_2018)~NA_character_,TRUE~"CD"))%>%
  mutate(d_capable=case_when(prop_d_2018>0.001 | prop_d_2019 >0.001~"Y",is.na(prop_d_2018) & is.na(prop_d_2019)~NA_character_,TRUE~"N"))%>%
  dplyr::rename(field_bleach=mean_bleach, expt_bleach=mean_exp_bleach,colony=genotype, block=block.x)%>%
  dplyr::select(id,colony,prop_d_2018,prop_d_2019,d_capable,symbiont,field_bleach, expt_bleach,initial_pam, pam_ed, health_ed, survivor,block,site,depth_m,sed_mean,rms_mean,height_mean,overall_min, overall_max, overall_mean_daily_range,overall_residual,hrs_above_30, total_dhw,summer_min, summer_mean, summer_sd,summer_mean_daily_range)%>%
  mutate(field_bleach_bin = field_bleach /3)

#saveRDS(population_data, "./output/population_data")
rm(expt_bleach, pam_ed, pam_initial, population_data, health_ed)

#### FIELD BLEACH x PAM ED REGRESSION & CORRELATION             ####
pam_reg<-readRDS("./output/ed20_pam_values")%>%
  left_join(.,metadata,by="id")%>%
  dplyr::filter(group=="clonality",drop_clones=="keep")%>%
  dplyr::select(id,ed,se,lwr,uppr,mean_bleach,)%>%
  mutate(bleach_bin=mean_bleach/3)%>%
  mutate(bleach_beta=case_when(bleach_bin==1~0.99999,TRUE~bleach_bin))

#characterize distribution of ed values
length(pam_reg$ed)
summary(pam_reg$ed)
sd(pam_reg$ed)
IQR(pam_reg$ed)
boxplot(pam_reg$ed)
hist(pam_reg$ed, breaks = 50)
densityPlot(pam_reg$ed)
ks.test(pam_reg$ed, "pnorm", mean=mean(pam_reg$ed), sd=sd(pam_reg$ed))

#visualize 
pam_bleach_lm<-lm(ed~bleach_bin,pam_reg)
summary(pam_bleach_lm)
glance(pam_bleach_lm)
plot(pam_bleach_lm)

#correlation test
cor.test(x=pam_reg$ed,y=pam_reg$bleach_bin, method="pearson")
#visualize
ggplot(pam_reg, aes(ed, bleach_bin))+geom_point()+geom_smooth(method="lm")

rm(pam_reg, pam_bleach_lm)
####
#### ####
#### SYMBIONT x PAM ED & FIELD BLEACHING ANOVA                  #### 
pop_data<-readRDS("./output/population_data")%>%mutate(symbiont=as.factor(symbiont))%>%filter(!is.na(symbiont))

#check expected symbiont effect on field bleaching performance
ggplot(pop_data,aes(x=symbiont, y=field_bleach))+geom_boxplot()
leveneTest(data=pop_data,field_bleach~symbiont)
welch_anova_test(pop_data, field_bleach~symbiont) # use welch for unequal variances in symbiont groups
tukey_hsd(pop_data, field_bleach~symbiont)

#check symbiont effect on experimental heat-stress performance (fv/fm)
ggplot(pop_data,aes(x=symbiont, y=pam_ed))+geom_boxplot()
leveneTest(data=pop_data,pam_ed~symbiont)
summary(aov(pam_ed~symbiont, data=pop_data))

#check symbiont effect on experimental heat-stress performance (health score)
ggplot(pop_data,aes(x=symbiont, y=expt_bleach))+geom_boxplot()
leveneTest(data=pop_data,expt_bleach~symbiont)
summary(aov(expt_bleach~symbiont, data=pop_data))

#### FIGURE 2 PAM ED x FIELD BLEACH + SYMBIONTS                 ####
library(cowplot); library(ggplotify); library(grid); library(ggpp); library(patchwork); library(gtable)

ED_pam_model<-readRDS("./output/ED_pam_model")
ED_pam<-readRDS("./output/ed20_pam_values")%>%
  rename(duration=ed)
ED_pam_fits<-readRDS("./output/edfits_pam")%>%
  mutate(dummy=1)%>%
  mutate(scale=(100-ed)/100)

survivors<-readRDS("./output/survivors")%>%
  dplyr::select(id,survivor)

Fig2A_data<-left_join(metadata,ED_pam,by="id")%>%
  dplyr::select(id,group,genotype,site,block,mean_bleach,prop_d_2018,prop_d_2019,duration,drop_clones)%>%
  left_join(survivors, by="id")%>%
  mutate(sym_2018=case_when(prop_d_2018>0.9~"D",prop_d_2018<0.1~"C",between(prop_d_2018,0.1,0.9)~"mix"))%>%
  mutate(bin_surv=case_when(survivor=="Y"~1,survivor=="N"~0))%>%
  mutate(surv_label=case_when(survivor=="Y"~"Survivors",TRUE~"DEAD"))%>%
  mutate(sym_2018=case_when(sym_2018=="mix"~"C/D",TRUE~sym_2018))

Fig2B_data<-Fig2A_data%>%dplyr::filter(group=="clonality",drop_clones=="keep")

pam_tile<-
  ggplot(ED_pam_fits,aes(dummy,ed))+
  geom_tile(aes(fill=lm_r2,height=2, width=1),color="white",show.legend=FALSE)+
  geom_segment(aes(x=0.45,xend=1.5,y=20,yend=20),alpha=0.5,size=0.3, color="red", linetype="dashed")+
  scale_y_reverse(limit=c(50,0),expand=c(0,0))+
  theme(panel.grid.major = element_blank())+
  scale_fill_gradient2(low = "white", mid ="white",midpoint= 0.03, high = "green",limits=c(0, 0.13), breaks=(c(0.125,0.1, 0.075,0.05, 0.025, 0)))+
  theme_classic(base_size=8)+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        #axis.line.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.line.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.ticks.length = unit(0, "cm"))+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"));pam_tile

tile_legend<-
  get_legend(ggplot(ED_pam_fits,aes(dummy,ed))+
               geom_tile(aes(fill=lm_r2),show.legend=TRUE)+
               #guides(fill = guide_legend(reverse = TRUE))+
               scale_fill_gradient2(guide = guide_colorbar(reverse = TRUE),low = "white", mid ="white",midpoint= 0.03, high = "green",limits=c(0, 0.13), breaks=(c(0.12, 0.09, 0.06,0.03)))+
               theme(legend.key.size = unit(0.10, 'in'),
                     panel.background = element_rect(fill = "transparent",color=NA_character_), 
                     plot.background = element_rect(fill = "transparent", colour = NA_character_),
                     legend.key = element_rect(fill = "transparent"),
                     legend.title = element_text(size=5), 
                     legend.text = element_text(size=5),
                     legend.key.width= unit(0.10, 'in'),
                     legend.key.height= unit(0.15, 'in'),
                     legend.background=element_rect(fill="transparent",color=NA))+
               labs(fill=expression(paste("")),size=2));plot(tile_legend) #CDW x FBS R"^"2

quartz(w=5,h=4)
pam_decay<-ggplot(ED_pam_model)+
  geom_line(aes(duration,predicted,group=id),color="grey20",alpha=0.5,size=0.2)+
  #geom_line(data=ED_pam_model%>%filter(id=="3105"),aes(duration,predicted,group=id),color="blue",alpha=1,size=1)+
  geom_hline(yintercept=0.8, linetype="dashed",size=0.6, color="red")+
  geom_histogram(data=ED_pam,aes(x=duration, y=(..count../200)+0.5,fill=..x..),alpha=0.9,color="black",binwidth=0.6,size=0.25)+
  scale_fill_gradient2(low = "black", mid = "grey50",high = "white")+  
  annotate("text",x=2.6,label="20% Fv/Fm",y=0.815,color="red", size=2.5)+
  annotate("text",x=2.6,label=" reduction",y=0.785,color="red", size=2.5)+
  annotate("text",x=19.25, label="Field Bleaching ~", y=0.96,color="black", size=2.2,hjust=1)+
  annotate("text",x=19.25, label="ED20[~Fv/Fm]", parse=TRUE, y=0.93,color="black", size=2.2,hjust=1)+
  annotate("text",x=19.25, label="R^2", parse=TRUE, y=0.9,color="black", size=2.2,hjust=1)+
  scale_x_continuous(breaks=c(5,10,15,20),expand=c(0,0))+
  scale_y_continuous(breaks=c(0.50,0.60, 0.70, 0.80, 0.90,1.00,1),expand=c(0,0))+
  theme_classic(base_size=8)+
  theme(axis.title.y = element_text(margin = margin(r = 10)),axis.title.x=element_text(margin=margin(t=5),hjust=0.54))+
  labs(x= "Cumulative Heat Stress", y= "Relative Fv/Fm")+
  theme(axis.title.y = element_text(hjust = 0.4),legend.position ="none")+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  coord_cartesian(xlim=c(0,24), ylim=c(0.5,1))+
  inset_element(pam_tile,0.95,0,1,1, align_to="panel",clip=TRUE)+
  inset_element(tile_legend,right=0.92,left=0.82,bottom=0.83,top=0.95, align_to="panel",clip=TRUE);pam_decay

quartz(w=2.5,h=2.5)
pam_scat<-
  ggplot(Fig2B_data%>%dplyr::filter(drop_clones=="keep"),aes(duration, mean_bleach))+
  geom_point(pch=21,fill="grey60",size=1.8, color="black",stroke=0.2)+
  geom_smooth(method="lm", color="grey30")+
  theme_classic(base_size=8)+
  theme(axis.title.y = element_text(margin = margin(r = 2)),axis.title.x=element_text(margin=margin(t=5),hjust=0.54))+
  scale_x_continuous(limits=c(5,20), breaks=c(10,15),expand=c(0,0))+
  scale_y_continuous(limits=c(0,3.4), breaks=c(0,1,2,3),expand=c(0,0))+
  theme(legend.position = c(0.8,0.105),
        legend.margin = margin(0, 0, 0, 0),
        legend.title = element_blank(),
        legend.text = element_text(size=5.5),
        legend.spacing.x = unit(0, 'in'))+
  labs(x= bquote(ED20[~Fv/Fm]), y= "Field Bleaching Score" )+
  theme(plot.margin = unit(c(0, 0, 0, 0.2), "cm"))+
  coord_cartesian(xlim=c(5,19.4), ylim=c(0,3.1))+
  annotate("text",x=17.8,y=1.5,label= "r=0.35\np<0.001",size=2.2,hjust=1)+ #from FIELD BLEACH x PAM ED REGRESSION & CORRELATION section above
  annotate("text",x=5.35,y=0.3,label= "More Field\nBleaching",size=2.2,hjust=0)+
  annotate("text",x=5.35,y=2.85,label= "Less Field\nBleaching",size=2.2,hjust=0);pam_scat

sym_colors = c("#73959D", "#F6D064", "#AD8599")

quartz(height=0.5, width=2)
symbiont_legend<-get_legend(ggplot(Fig2B_data%>%filter(!is.na(sym_2018)))+
                              geom_density(aes(duration, color = sym_2018), size=1, show.legend=TRUE, key_glyph="timeseries")+
                              scale_color_manual(values = sym_colors)+
                              labs(color = "Symbionts:", title = "C") +
                              theme_classic(base_size=6)+
                              theme(legend.direction="horizontal",
                                    legend.key.size =unit(0.1, 'in')));plot(symbiont_legend)

pam_dens_x<-
  ggplot(Fig2B_data%>%filter(!is.na(sym_2018)))+
  geom_density(aes(duration, color = sym_2018,fill=sym_2018), size=0.3, show.legend=FALSE, key_glyph="timeseries", alpha=0.6)+
  scale_color_manual(values = sym_colors)+
  scale_fill_manual(values = sym_colors)+
  labs(y="Density",color = "Symbionts") +
  theme_classic(base_size=8)+
  theme(legend.position = c(0.2,0.8),legend.background = element_rect(linetype = 1, size = 0.5, colour = 1))+
  theme(plot.title=element_text(vjust = -12,hjust = 0.05,size = 12))+
  theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.line.x=element_blank(),axis.ticks.x=element_blank())+
  theme(axis.title.y = element_text(margin = margin(r = 5),size=6))+
  theme(axis.text.x=element_blank())+
  scale_x_continuous(limits=c(5,20.2), breaks=c(5,10,15,20),expand=c(0,0))+
  scale_y_continuous(limits=c(-0.01,0.45), breaks=c(0.0, 0.1,0.2,0.3,0.4),expand=c(0,0))+
  theme(plot.margin = unit(c(0, 0, 0, 0.2), "cm"))+
  annotate("text",x=7,y=0.3,label= stringr::str_wrap("p=0.236",width = 10),size=2.2);pam_dens_x #value from SYMBIONT x PAM ED & FIELD BLEACHING section above

pam_dens_y<-
  ggplot(Fig2B_data%>%filter(!is.na(sym_2018)))+
  geom_density(aes(mean_bleach, color = sym_2018,fill = sym_2018), size=0.3, show.legend=FALSE, alpha=0.6)+
  scale_color_manual(values = sym_colors)+
  scale_fill_manual(values = sym_colors)+
  theme_classic(base_size=8)+
  labs(y="Density")+
  theme(axis.title.y=element_blank(),axis.text.y=element_blank(),axis.line.y=element_blank(),axis.ticks.y=element_blank())+
  theme(axis.title.x = element_text(margin=margin(t=4),size=6))+
  coord_flip() + 
  scale_x_continuous(limits=c(0,3.1), breaks=c(1,2,3), expand=c(0,0))+
  scale_y_continuous(limits=c(0,1.6), breaks= c(0,0.5,1,1.5),expand=c(0,0))+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  annotate("text",x=0.35,y=0.6,label= stringr::str_wrap("p<0.001",width = 10),size=2.2,hjust=0);pam_dens_y #value from SYMBIONT x PAM ED & FIELD BLEACHING section above

quartz(w=7.2, h=3)
x<-cowplot::align_plots(pam_decay,pam_scat,pam_dens_y,align="h",axis="b")
Fig2<-
  plot_grid(x[[1]],
            plot_grid(pam_dens_x,x[[2]],nrow=2,align="v",rel_heights=c(1.2,4)),
            plot_grid(NULL,x[[3]],nrow=2,rel_heights=c(1.2,4)),
            # plot_grid(NULL,x[[4]],nrow=2,rel_heights=c(0.9,4)),
            nrow=1,rel_widths=c(6,4,1), 
            labels=c("A","B",""), 
            label_size=10, 
            label_x =c(0.02,-0.05,0))+
  inset_element(symbiont_legend,right=1,left=0.8,bottom=0.87,top=0.95);Fig2

rm(ED_pam, ED_pam_fits, ED_pam_model, Fig2, Fig2A_data, Fig2B_data, pam_decay, pam_dens_x, pam_dens_y, pam_scat, symbiont_legend, x, sym_colors,pam_tile, tile_legend, survivors)

#### ####
#### GENOTYPE REPLICATION ANALYSIS                              ####

rte_pam<-readRDS("./output/ed20_pam_values")%>%
  left_join(metadata, by="id")%>%
  dplyr::filter(experiment=="RTE"|experiment=="clonality")

ggplot(rte_pam%>%dplyr::filter(experiment=="RTE"),aes(x=genotype, y=ed))+geom_boxplot()
leveneTest(data=rte_pam%>%dplyr::filter(experiment=="RTE"),ed~genotype)
welch_anova_test(ed~genotype, data=rte_pam%>%dplyr::filter(experiment=="RTE"))

#visualize
ggplot(rte_pam%>%dplyr::filter(experiment=="RTE"),aes(x=reorder(genotype,ed,median),y=ed))+geom_boxplot()

#caculate broadsense heritability (prop of variance explained by genotype out of the total variance observed)
library(heritability)
BSH_calc<-rte_pam%>%dplyr::filter(experiment=="RTE")
repeatability(BSH_calc$ed, BSH_calc$genotype, line.repeatability = FALSE)
# BSH = 0.39     $repeatability

#### SITE X EXPT PERFORMANCE ANALYSIS & MODEL                   ####

pop_data<-readRDS("./output/population_data")

leveneTest(data=na.omit(pop_data%>%dplyr::select(site,pam_ed,block)),pam_ed~site)
site_effect<-aov(pam_ed~site,data=na.omit(pop_data%>%dplyr::select(site,pam_ed,block)));summary(site_effect)
block_effect<-aov(pam_ed~block,data=na.omit(pop_data%>%dplyr::select(site,pam_ed,block)));summary(block_effect)

#visualize
ggplot(na.omit(pop_data%>% dplyr::select(site,pam_ed,block)),aes(x=reorder(site,pam_ed, FUN=IQR),y=pam_ed, fill=block))+geom_boxplot(alpha=0.5)

## linear modeling
# get variable names
names(pop_data)

# check variables for correlation
library(GGally)
pdf("output/figures/pairs.pdf", height=16, width=16)
ggpairs(pop_data[c("field_bleach_bin","pam_ed", "initial_pam","initial_rgb","survivor","sed_mean","height_mean", "overall_residual", "total_dhw", "summer_mean", "summer_min", "summer_sd", "summer_mean_daily_range", "expt_bleach", "rgb_ed", "depth_m", "rms_mean", "overall_mean_daily_range", "hrs_above_30", "prop_d_2018",  "overall_max", "overall_min")])
dev.off()

#collinearity adjustments:
#rms_mean and height_mean are highly correlated, leave out both b/c these are measured at block level not at site level and no structuring by block is indicated

#overall_residual and summer_mean are highly correlated, use 'overall_residual' (difference of individual site from bay average - may capture site-specific aspect of temperature)

#prop_d and initial_pam are highly correlated, use 'prop_d' (symbiont community is known driver) for overall model, exclude in site variable model

#pam_ed is correlated with rgb_ed and expt_bleaching score, use 'pam_ed' (experimental heat stress response)

#summer_mean, summer_min, summer_sd, summer_mean_daily_range, total_dhw, overall_mean_daily_range, hrs_above_30, overall_max, and overall_min are ALL inter-correlated, use 'overall_mean_daily_range' or 'hrs_above_30' as most representative of site thermal history to impact acclimatization

#overall_mean_daily_range is highly correlated with hrs_above_30, overall_max, and overall_min, use 'overall_mean_daily_range'

#depth_m is correlated with summer_min, summer_sd, and summer_mean_daily_range, include 'depth_m' as it has potential importance as env factor in addition to or separate from site temperature


# model experimental performance (PAM_ED20) based on source site characteristics (and symbionts):
Emod1 <- lm(pam_ed ~ sed_mean + overall_residual + overall_mean_daily_range + depth_m, data=pop_data)
drop1(Emod1, test="F")
summary(Emod1)
#AR2 -0.01

#drop sed_mean
Emod2 <- lm(pam_ed ~  overall_residual + overall_mean_daily_range + depth_m, data=pop_data)
drop1(Emod2, test="F")
summary(Emod2)
#AR2 0

#drop overall_residual
Emod3 <-  lm(pam_ed ~ overall_mean_daily_range + depth_m, data=pop_data)
drop1(Emod3, test="F")
summary(Emod3)
#AR2 0

#drop overall_mean_daily_range
Emod4 <-  lm(pam_ed ~  depth_m, data=pop_data)
drop1(Emod4, test="F")
summary(Emod4)

# AIC value increasing with no significant predictors

#### ####
#### FIELD BLEACH x EXPT SURVIVORSHIP                           ####
#test relationship
t.test(mean_bleach ~ survivor, data=survivors)

#visualize relationship
ggplot(data=survivors) +
  geom_boxplot(aes(x=survivor, y=mean_bleach))

#chi square test (by symbiont group)

survivor_chi2<-readRDS("output/frag_bleachdata")%>%
  left_join(metadata, by="id")%>%
  filter(experiment=="clonality"|experiment=="RTE")%>%
  filter(timepoint==1)%>%
  right_join(as_tibble(readRDS("output/survivors")%>%
                         dplyr::select(-group)), by="id")%>%
  filter(experiment=="clonality")%>%
  mutate(D_dom=case_when(prop_d_2018>=0.2~"1",TRUE~"0"))%>%
  dplyr::select(survivor,D_dom)%>%
  mutate(survivor=case_when(survivor=="Y"~"1",survivor=="N"~"0"))%>%
  drop_na()

chisq.test(survivor_chi2$survivor, survivor_chi2$D_dom, correct=FALSE,simulate.p.value = TRUE)

# Fisher test
survivor_fisher<-readRDS("output/frag_bleachdata")%>%
  left_join(metadata, by="id")%>%
  filter(experiment=="clonality"|experiment=="RTE")%>%
  filter(timepoint==1)%>%
  right_join(as_tibble(readRDS("output/survivors")%>%
                         dplyr::select(-group)), by="id")%>%
  filter(experiment=="clonality")%>%
  mutate(symbiont=case_when(prop_d_2018<=0.2~"C",prop_d_2018>=0.2~"D",TRUE~"M"))%>%
  dplyr::select(survivor,symbiont)%>%
  mutate(survivor=case_when(survivor=="Y"~"1",survivor=="N"~"0"))%>%
  drop_na()

chisq.test(survivor_fisher$survivor, survivor_fisher$symbiont)$expected
fisher.test(survivor_fisher$survivor, survivor_fisher$symbiont)

# t.test
survivor_t<-readRDS("output/frag_bleachdata")%>%
  left_join(metadata, by="id")%>%
  filter(experiment=="clonality"|experiment=="RTE")%>%
  filter(timepoint==1)%>%
  right_join(as_tibble(readRDS("output/survivors")%>%
                         dplyr::select(-group)), by="id")%>%
  filter(experiment=="clonality")%>%
  dplyr::select(survivor,prop_d_2018)%>%
  mutate(survivor=case_when(survivor=="Y"~"1",survivor=="N"~"0"))%>%
  drop_na()

t.test(prop_d_2018~survivor, data=survivor_t)

# heat stress test survival as diagnostic test of future bleaching response
test<-survivors%>%filter(experiment=="clonality")%>%
  filter(drop_clones=="keep")%>%
  dplyr::select(survivor, mean_bleach)%>%
  mutate(survivor=as_factor(survivor))%>%
  drop_na()%>%
  mutate(diagnostic=case_when(survivor=="Y"& mean_bleach>2~"TP",
                              survivor=="N"& mean_bleach>2~"FN",
                              survivor=="Y"& mean_bleach<=2~"FP",
                              survivor=="N"& mean_bleach<=2~"TN",
                              TRUE~"other"))
  table(test$diagnostic)

ggplot(test)+geom_boxplot(aes(x=survivor, y=mean_bleach))

test2<-rbind(c(16,1),c(63,42))
library(bdpv)
BDtest(test2,pr=0.6)


#### FIGURE 3 HEALTH SCORE X FIELD BLEACH & SURVIVORSHIP        ####
library(cowplot); library(ggplotify); library(grid); library(ggpp); library(patchwork); library(gtable)

survivorship<-survivors%>%
  dplyr::select(id,survivor)

ED_health_model<-readRDS("./output/ED_health_model")%>%
  left_join(survivorship, by="id")
ED_health<-readRDS("./output/ed20_health_values")%>%
  rename(duration=ed)
ED_health_fits<-readRDS("./output/edfits_health")%>%
  mutate(dummy=1)%>%
  mutate(scale=(100-ed)/100)

surv_health_mod<-readRDS("output/surv_health_mod")
nonsurv_health_mod<-readRDS("output/nonsurv_health_mod")

Fig3_data<-left_join(metadata,ED_health,by="id")%>%
  dplyr::select(id,group,genotype,site,block,mean_bleach,prop_d_2018,prop_d_2019,duration,drop_clones)%>%
  left_join(survivorship, by="id")%>%
  mutate(sym_2018=case_when(prop_d_2018>0.9~"D",prop_d_2018<0.1~"C",between(prop_d_2018,0.1,0.9)~"mix"))%>%
  mutate(bin_surv=case_when(survivor=="Y"~1,survivor=="N"~0))%>%
  mutate(surv_label=case_when(survivor=="Y"~"Survivors",TRUE~"DEAD"))%>%
  mutate(sym_2018=case_when(sym_2018=="mix"~"C/D",TRUE~sym_2018))%>%
  dplyr::filter(group=="clonality",drop_clones=="keep")

Fig3C_data<-readRDS("output/frag_bleachdata")%>%
  left_join(metadata, by="id")%>%
  dplyr::filter(experiment=="clonality")%>%
  left_join(survivorship, by="id")%>%
  mutate(exp_bleach=case_when(exp_bleach<=1~1,TRUE~exp_bleach))%>%
  mutate(exp_bleach=exp_bleach-1)%>%
  group_by(id)%>%
  mutate(base_bleach=case_when(timepoint==1~exp_bleach,TRUE~NA_integer_))%>%
  fill(base_bleach)%>%
  mutate(prop_bleach=exp_bleach/base_bleach)%>%
  left_join(tempdata, by="date")


### stats for health score linear regression
###
all_health_mod<-lmer(data=ED_health_model, predicted~duration+survivor+(1|id )) #p<0.001

health_decay<-
  ggplot(Fig3C_data)+
  theme_classic(base_size=8)+
  theme(legend.position ="none",axis.title.x=element_text(margin=margin(t=5),hjust=0.55),axis.title.y = element_text(margin = margin(r = 10)))+
  #geom_jitter(aes(cumulative25, prop_bleach,group=id,fill=survivor),pch=21,size=1, color="black",stroke=NA,height=0.05,width=0.25)+
  geom_line(data=ED_health_model%>%filter(survivor=="N"),aes(duration, predicted,group=id),alpha=0.3,linewidth=0.9, color="grey80")+
  geom_line(data=ED_health_model%>%filter(survivor=="Y"),aes(duration, predicted,group=id),alpha=0.3,linewidth=0.9, color="seagreen1")+
  geom_line(data=nonsurv_health_mod, aes(accumulated, predicted),color="grey60",linewidth=1)+
  geom_line(data=surv_health_mod, aes(accumulated, predicted),color="seagreen3",linewidth=1)+
  geom_hline(yintercept=0.8, linetype="dashed",linewidth=0.4, color="red")+
  #scale_fill_manual(values=c("gray60", "seagreen2"))+
  #scale_color_manual(values=c("gray50", "seagreen2"))+
  annotate("text",x=15.25,label="20% decline",y=0.83,color="red", size=2.5)+
  annotate("text",x=15.25,label=" in health metric",y=0.77,color="red", size=2.5)+
  geom_point(aes(x=7.6,y=0.25), fill="seagreen2", shape=22,color="black",size=3, stroke=0.2)+
  annotate("text", x=7.95,y=0.25, label = "Survived", color="black", size=2.2,hjust=0)+
  geom_point(aes(x=7.6,y=0.18), fill="grey60", shape=22, color="black", size=3, stroke=0.2)+
  annotate("text", x=7.95,y=0.18, label = "Died", color="black", size=2.2,hjust=0)+
  annotate("text",x=7.5,y=0.11,label= "p<0.001",size=2.2,hjust=0)+
  scale_x_continuous(limits=c(6.7,16.67), breaks=c(8,10,12,14,16),expand=c(0,0))+
  scale_y_continuous(breaks=c(0,0.20, 0.40, 0.60, 0.80,1.00,1),expand=c(0,0))+
  labs(x= "Cumulative Heat Stress", y= "Relative Health Score");health_decay


## Health ED20 x Field Bleach
#correlation test
cor.test(x=Fig3_data$duration,y=Fig3_data$mean_bleach, method="pearson")
#visualize 
health_scat<-
  ggplot(Fig3_data,aes(duration, mean_bleach))+
  geom_smooth(method="lm", fill="grey80",color="black", linewidth=0.5)+
  geom_point(data=Fig3_data%>%filter(!surv_label=="Survivors"),aes(duration, mean_bleach), color="grey60",key_glyph=rectangle_key_glyph(fill = color, padding = margin(2,2,2,2)), size=2)+
  geom_point(data=Fig3_data%>%filter(surv_label=="Survivors"),aes(duration, mean_bleach), color="seagreen2",key_glyph=rectangle_key_glyph(fill = color, padding = margin(2,2,2,2)), size=2)+
  #scale_color_manual(breaks = "Survivors", values=c("seagreen2"))+
  theme_classic(base_size=8)+
  theme(axis.title.y = element_text(margin = margin(r = 10)),axis.title.x=element_text(margin=margin(t=5),hjust=0.6))+
  scale_x_continuous(limits=c(6,14.15), breaks=c(8,10,12,14),expand=c(0,0))+
  scale_y_continuous(limits=c(0,3.4), breaks=c(0,1,2,3),expand=c(0,0))+
  theme(legend.position = c(0.8,0.105),
        legend.margin = margin(0, 0, 0, 0),
        legend.title = element_blank(),
        legend.text = element_text(size=5.5),
        legend.spacing.x = unit(0, 'in'))+
  labs(x=bquote(ED20[~Health~Score]), y="Field Bleaching Score")+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  coord_cartesian(xlim=c(6.7,14.15), ylim=c(0,3.1))+
  annotate("text",x=13.8,y=0.3,label= "r=0.138\np=0.131",size=2.2,hjust=1)+
  annotate("text",x=6.9,y=0.3,label= "More Field\nBleaching",size=2.2,hjust=0)+
  annotate("text",x=6.9,y=2.85,label= "Less Field\nBleaching",size=2.2,hjust=0);health_scat

### stats for survivors 
###
survivor_t<-t.test(mean_bleach ~ survivor, data=survivors)

surv_box<-
  ggplot(data=Fig3_data%>%filter(!is.na(survivor)),aes(x=survivor, y=mean_bleach, fill=survivor, alpha=0.5)) +
  geom_boxplot()+
  scale_fill_manual(values=c("gray60", "seagreen2"))+
  theme_classic(base_size=8)+
  labs(x= "Survivor")+
  scale_x_discrete(labels = c('No','Yes'))+
  scale_y_continuous(limits=c(0,3.1), breaks=c(1,2,3),expand=c(0,0))+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  theme(legend.position="none",axis.title.y=element_blank(),axis.title.x=element_text(margin=margin(t=5)))+
  annotate("text",x=1.5,y=0.2,label= "p<0.001",size=2.2);surv_box

quartz(h=2.6, w=7.2)
plot_grid(health_decay,NULL,health_scat,surv_box,align="h",axis="b", nrow=1,rel_widths = c(4,0.1,3.8,0.9),labels = c('A', '','B','C'), hjust=c(-1,0,-0.2,1.6),label_size=10,scale=1)+theme(plot.margin=margin(5.2,5.2,5.2,5.2)) 

rm(all_health_mod, ED_health, ED_health_fits, ED_health_model, Fig3_data, Fig3C_data, health_decay, health_scat, nonsurv_health_mod, surv_box, surv_health_mod, survivor_t, survivorship)
#### ####
#### MODELING FIELD BLEACH BY PRIOR INFORMATION                 ####
pop_data<-readRDS("./output/population_data")

# model field bleaching performance based on prior information (experimental metrics, symbiont community, and site characteristics)
# reduce site temperature metrics and wave metrics based on correlation check above in SITE MODEL

Fmod1 <- lm(field_bleach_bin ~ sed_mean + overall_residual + overall_mean_daily_range + depth_m + prop_d_2018 + pam_ed  + health_ed + survivor , data=pop_data)
drop1(Fmod1, test="F")
summary(Fmod1)
#AR2 0.38

#drop survivor and health_ed
Fmod2 <- lm(field_bleach_bin ~ sed_mean + overall_residual + overall_mean_daily_range + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod2, test="F")
summary(Fmod2)
#AR2 0.39

#drop sed_mean
Fmod3 <- lm(field_bleach_bin ~ overall_residual + overall_mean_daily_range + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod3, test="F")
summary(Fmod3)
#AR2 0.39

#drop overall_residual (note: overall_mean_daily_range is contributing to the model while overall_residual has not)
Fmod4 <- lm(field_bleach_bin ~ overall_mean_daily_range + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4, test="F")
summary(Fmod4)
#AR2 0.40

#visualize model
test<-as.data.frame(predict(Fmod4, newdata=pop_data))%>%bind_cols(pop_data$field_bleach_bin)%>%rename(predicted=1,actual=2)
ggplot(test)+
  geom_point(aes(predicted, actual))+geom_smooth(aes(predicted, actual),method="lm")
# all remaining variables appear to have explanatory power, depth_m has least, but removing it will lower AIC by  ~5 points

#try drop depth_m anyway
Fmod5 <- lm(field_bleach_bin ~ overall_mean_daily_range +  prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod5, test="F")
summary(Fmod5)
#AR2 0.36 (biggest drop so far...stick with Fmod4 version )

library("sjPlot")
tab_model(Fmod4, pred.labels = c("Intercept", "mean daily temperature range at site", "nominal site depth", "prior proportion of clade-D symbionts", "DHW heat-stress dose at 20% fv/fv decline"), dv.labels="Field Health Score",file ="./output/Fmodel_table.doc")

# also check swapping in collinear hrs_above_30 for overall_mean_daily range
Fmod4.1 <- lm(field_bleach_bin ~ hrs_above_30 + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4.1, test="F")
summary(Fmod4.1)
# hrs_above_30 is significant, but model loses power AR2 34 and depth_m loses significance

# check swapping in collinear overall_max for overall_mean_daily range
Fmod4.2 <- lm(field_bleach_bin ~ overall_max + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4.2, test="F")
summary(Fmod4.2)
# overall_max is significant, but model loses power AR2 35 and depth_m loses significance

# check swapping in collinear overall_min for overall_mean_daily range
Fmod4.3 <- lm(field_bleach_bin ~ overall_min + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4.3, test="F")
summary(Fmod4.3)
# overall_min is significant, model similar to w/ overall_mean_daily_range AR2 38 and depth_m still significant

# check swapping in collinear summer_mean_daily_range for overall_mean_daily range
Fmod4.4 <- lm(field_bleach_bin ~ summer_mean_daily_range + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4.4, test="F")
summary(Fmod4.4)
# summer_mean_daily_range is significant to w/ overall_mean_daily_range AR2 38 and depth_m still significant

# check swapping in collinear summer_min for overall_mean_daily range
Fmod4.5 <- lm(field_bleach_bin ~ summer_min + depth_m + prop_d_2018 + pam_ed, data=pop_data)
drop1(Fmod4.5, test="F")
summary(Fmod4.5)
# summer_min is significant, AR2 36 and depth_m still significance

# check depth alone
Fmod4.6 <- lm(field_bleach_bin ~ depth_m, data=pop_data)
summary(Fmod4.6)

ggplot(pop_data,aes(x=depth_m, y=field_bleach_bin))+
  geom_jitter()+
  geom_smooth(method="lm")

library(hier.part)
Fmod4_part <- na.omit(pop_data[c("field_bleach_bin", "overall_mean_daily_range", "depth_m", "prop_d_2018", "pam_ed" )])
Fmod4_hier_part<-hier.part(Fmod4_part$field_bleach_bin, Fmod4_part[,2:5])
Fmod4_perc<-Fmod4_hier_part$I.perc

#saveRDS(Fmod4_perc, "./output/Fmodel_variance_partitions")
rm(Fmod1, Fmod2, Fmod3, Fmod4, Fmod4_part, Fmod4_hier_part, Fmod4_perc, Fmod4.1, Fmod4.2, Fmod4.3, Fmod4.4, Fmod4.5,Fmod4.6, Fmod5, test)

#### FIGURE 4 MODEL OUTCOMES                                    ####
library(scales);library("sjPlot")

pop_data<-readRDS("./output/population_data")%>%
  mutate("Field Health Score" = "field_bleach_bin")

model_data<-as_tibble(readRDS("./output/Fmodel_variance_partitions"), rownames="variable")%>%
  mutate(variable=factor(variable,levels =c("prop_d_2018","pam_ed","overall_mean_daily_range","depth_m")))%>%
  mutate(labels=case_when(variable=="prop_d_2018"~"Symbiont Community", variable=="pam_ed"~"Experimental Performance", variable=="depth_m"~"Habitat (water depth)", variable=="overall_mean_daily_range"~"Habitat (thermal history)"))

FHS_model <- lm(field_bleach_bin ~ prop_d_2018 + overall_mean_daily_range  +  pam_ed + depth_m, data=pop_data)

#table of model for viewer
tab_model(FHS_model, pred.labels = c("Intercept", "prior proportion of clade-D symbionts", "mean daily temperature range at site" , "DHW heat-stress dose at 20% fv/fv decline","nominal site depth"), dv.labels="Field Health Score")

#table of model for export
tab_model(FHS_model, pred.labels = c("Intercept", "prior proportion of clade-D symbionts", "mean daily temperature range at site", "DHW heat-stress dose at 20% fv/fv decline","nominal site depth"), dv.labels="Field Health Score", file ="./output/figures/Fmodel_table.doc")

#hierarchical partitioning bar plot
quartz(w=3, h=1)
Fig4<-
  ggplot(model_data,aes(x=reorder(labels, ind.exp.var), y = ind.exp.var))+
  geom_bar(stat = "identity", fill="grey")+
  theme_classic(base_size = 8)+
  labs(y="% Independent Effects")+
  theme(axis.text.x =element_text(color="black"),axis.title.x = element_text(size=6,margin = margin(t = 5)))+
  theme(axis.text.y =element_text(color="black"),axis.title.y = element_text(margin = margin(r = 10)))+
  theme(axis.title.y=element_blank(),axis.ticks.y=element_blank())+
  scale_y_continuous(expand=c(0.01,0),limits=c(0,52), breaks=c(0,10,20,30,40,50))+
  coord_flip()+
  theme(axis.text.y = element_text(hjust=0));Fig4

rm(FHS_model, model_data, Fig4)

#### ####
#### SUPPLEMENTAL ####
#### FIGURE S1 - RAW PAM DATA                                   ####
quartz(width=7.2, height=2.4)
ggplot(pamdata%>%filter(date<="2018-03-01"),aes(x=date,y=fv_fm))+
  geom_jitter(color="grey50")+
  geom_smooth(method="loess",color="black")+
  theme_classic()+
  labs(y="Fv/Fm", x="Date")
# raw fv/fm values
#### FIGURE S2 - ED EXAMPLE                                     ####
library(cowplot); library(ggplotify); library(grid); library(ggpp); library(patchwork); library(gtable)

ED_pam_model<-readRDS("./output/ED_pam_model")
ED_pam<-readRDS("./output/ed20_pam_values")%>%
  rename(duration=ed)

overall_pam_fig<-ggplot(ED_pam_model)+
  geom_line(aes(duration,predicted,group=id),color="grey50",alpha=1,size=0.1)+
  geom_line(data=ED_pam_model%>%filter(id=="675"),aes(duration,predicted,group=id),color="blue",alpha=1,size=0.4)+
  scale_x_continuous(breaks=c(2.5,5,7.5,10,12.5,15,17.5,20),expand=c(0,0))+
  scale_y_continuous(breaks=c(0.50,0.60, 0.70, 0.80, 0.90,1.00,1),expand=c(0,0))+
  theme_classic(base_size=10)+
  theme(axis.title.y = element_text(margin = margin(r = 10)),axis.title.x=element_text(margin=margin(t=5),hjust=0.54))+
  labs(x= "Cumulative Heat Stress", y= "Relative Fv/Fm")+
  theme(axis.title.y = element_text(hjust = 0.4),legend.position ="none")+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  coord_cartesian(xlim=c(0,24), ylim=c(0.5,1.01));overall_pam_fig

isolate_pam_fig<-ggplot(ED_pam_model)+
  geom_line(data=ED_pam_model%>%filter(id=="675"),aes(duration,predicted,group=id),color="blue",alpha=1,size=1)+
  geom_hline(yintercept=0.8, linetype="dashed",size=0.6, color="red")+
  annotate("text",x=2.6,label="20% Fv/Fm",y=0.815,color="red", size=2.5)+
  annotate("text",x=2.6,label=" reduction",y=0.785,color="red", size=2.5)+
  annotate("segment", x=12.45457, xend=12.45457, y=0.799, yend=0.501,color="red",arrow=arrow(ends="last",length = unit(.2,"cm"),angle=35))+
  annotate("text", x=20, y=0.65, label="ED20[~Fv/Fm]", parse=TRUE, color="black", hjust=0.5)+
  annotate("text", x=20, y= 0.6,label= "= 12.5", color="blue",hjust=0.5)+
  scale_x_continuous(breaks=c(2.5,5,7.5,10,12.5,15,17.5,20),expand=c(0,0))+
  scale_y_continuous(breaks=c(0.50,0.60, 0.70, 0.80, 0.90,1.00,1),expand=c(0,0))+
  theme_classic(base_size=10)+
  theme(axis.title.y = element_text(margin = margin(r = 10)),axis.title.x=element_text(margin=margin(t=5),hjust=0.54))+
  labs(x= "Cumulative Heat Stress", y= "Relative Fv/Fm")+
  theme(axis.title.y = element_text(hjust = 0.4),legend.position ="none")+
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+
  theme(axis.text.x = element_text(colour = c('black', 'black','black', 'black','blue', 'black', 'black', 'black')))+
  coord_cartesian(xlim=c(0,24), ylim=c(0.5,1.01), );isolate_pam_fig

quartz(width=7.2, height=2.4)
FigS2<-plot_grid(overall_pam_fig,NULL,isolate_pam_fig,nrow=1, rel_widths=c(4,0.2,4), labels=c("A","","B"));FigS2

#### FIGURE S3 - COMPARE ED LEVELS (PAM and HEALTH)             ####

pam_fits<-readRDS("./output/edfits_pam")
health_fits<-readRDS("./output/edfits_health")

pam_fits_plot<-ggplot(pam_fits,aes(x=ed,y=lm_r2))+
  geom_bar(stat="identity")+
  theme_classic(base_size = 10)+
  labs(y= Linear~Model~R^2, x= "PAM Fv/Fm ED Value")+
  scale_y_continuous(limits=c(0, 0.12),breaks=c(0,0.04, 0.08,0.12));pam_fits_plot

health_fits_plot<-ggplot(health_fits,aes(x=ed,y=lm_r2))+
  geom_bar(stat="identity")+
  theme_classic(base_size = 10)+
  labs(y= Linear~Model~R^2, x= "Health Score ED Value")+
  scale_y_continuous(limits=c(0, 0.12),breaks=c(0,0.04, 0.08,0.12));health_fits_plot

quartz(width=7.2, height=2.4)
FigS3<-plot_grid(pam_fits_plot,NULL,health_fits_plot,nrow=1, rel_widths=c(4,0.2,4), labels=c("A","","B"));FigS3
#### FIGURE S4 - SITE and GENOTYPE EFFECTS                      ####
library(cowplot); library(ggplotify); library(grid); library(ggpp); library(patchwork);library(corrr)

pop_data<-readRDS("./output/population_data")
site_pop_data<-pop_data%>%group_by(site)%>%summarise(mean=mean(pam_ed,na.rm=TRUE),sd=sd(pam_ed,na.rm=TRUE))%>%mutate(cv=mean/sd)
just_env<-read_tsv("data/Site Data/environment_data.txt")%>%clean_names()%>%left_join(site_pop_data, by="site")
just_env%>%correlate()%>%stretch()%>%
  ggplot(aes(x,y,fill=r))+geom_tile()+
  scale_fill_gradient(low="red",high='blue')

rte_pam<-readRDS("./output/ed20_pam_values")%>%
  left_join(metadata, by="id")%>%
  dplyr::filter(experiment=="RTE"|experiment=="clonality")%>%
  mutate(rte_genotype=parse_number(genotype))%>%
  mutate(reef=case_when(str_detect(rte_genotype,"24|52|55|144|208")~13,str_detect(rte_genotype,"162|163|24")~4,TRUE~NA_real_ ))

FigS4A<-
  ggplot(rte_pam%>%dplyr::filter(experiment=="RTE"),aes(x=reorder(rte_genotype,ed,median),y=ed))+
  geom_boxplot(alpha=0.5, fill="grey")+
  theme_classic(base_size = 8)+
  labs(x= "Genotype", y= bquote(ED20[~Fv/Fm]))+
  #theme(axis.title.y=element_blank(),axis.text.y=element_blank(),axis.line.y=element_blank(),axis.ticks.y=element_blank())+
  scale_y_continuous(limits=c(6,24), breaks=c(10,15,20), expand=c(0,0))+
  theme(axis.text.x = element_text(angle = 90,vjust=0.5))+
  #theme(plot.title=element_text(vjust = -8,hjust = 0.05,size = 32))+
  theme(axis.title.x = element_text(margin = margin(t = 12)))+
  theme(axis.title.y = element_text(margin = margin(r = 10)))+
  annotate("text",x=6.5,y=7,hjust=0,label= "p<0.0001",size=2.5)+
  annotate("text",x=6.5,y=8,hjust=0,label=deparse(bquote(H^'2'~'=0.39')),parse=TRUE, size=2.5);FigS4A

FigS4B<-
  ggplot(na.omit(pop_data%>% dplyr::select(site,pam_ed,block)),aes(x=reorder(site,pam_ed, median),y=pam_ed, fill=block))+
  geom_boxplot(alpha=0.5)+
  theme_classic(base_size = 8)+
  labs(x= "Site")+
  theme(axis.title.y=element_blank(),axis.text.y=element_blank(),axis.line.y=element_blank(),axis.ticks.y=element_blank())+
  scale_y_continuous(limits=c(6,24), breaks=c(10,15,20), expand=c(0,0))+
  theme(axis.text.x = element_text(angle = 90,vjust=0.5))+
  scale_fill_viridis_d(direction=1,name="Block")+
  theme(legend.position = c(0.3,0.9),legend.direction="horizontal",legend.background = element_rect(linetype = 1, size = 0.3, colour = 1),legend.key.width= unit(0.15, 'in'))+
  #theme(plot.title=element_text(vjust = -8,hjust = 0.05,size = 32))+
  theme(axis.title.x = element_text(margin = margin(t = 9)))+
  #theme(axis.title.y = element_text(margin = margin(r = 10)))+
  annotate("text",x=25,y=8,label= "Site   p=0.017", size=2.5,hjust=0)+
  annotate("text",x=25,y=7,label= "Block p=0.746", size=2.5, hjust=0);FigS4B

quartz(w=7.2, h=2.8)
FigS4<-plot_grid(FigS4A, FigS4B, ncol=2, nrow=1, align ="h", axis="b", rel_widths = c(1,2), labels="AUTO", label_size =12);FigS4







